name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    container:
      image: peijin/lwa-solar-pipehost
      env:
        PATH: /usr/local/bin:/usr/bin:/bin
        LD_LIBRARY_PATH: /usr/local/lib:/usr/lib:/lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov asdf numpy astropy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=ovrolwasolar --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml