```yaml
name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full Git history for Codecov

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Matches Python 3.8.18 from error output

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov asdf numpy astropy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e . # Install project as a package to resolve imports

      - name: Run tests with coverage
        run: |
          pytest tests/ --cov=ovrolwasolar --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Optional if repo is public
          files: ./coverage.xml
          fail_ci_if_error: true # Fail CI if Codecov upload fails